---
services:
# This is the OLLAMA Container
  ollama:
    container_name: ollama
    image: ollama/ollama
    volumes:
      - ./ollama:/root/.ollama
    tty: true
    restart: unless-stopped
    ports:
      - 11434:11434
    # networks: 
    #   - private

# This is the OpenWebUI Container
  webui:
    image: ghcr.io/open-webui/open-webui
    container_name: open-webui
    volumes:
      - ./openui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY=cGFzc3dvcmQxMjNeJSQK'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    # networks:
    #   - private

  # web:
  #   image: nginx:latest
  #   ports:
  #     - "80:80" 
  #     - "443:443" 
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
  #     # - ./certs:/etc/nginx/certs 
  #   depends_on:
  #     - ollama
  #   networks:
  #     - private
    
# networks:
#   private:
...